import numpy as np


def construct_transcorr_H(H_1body, H_2body, info):

    # Getting parameters!
    ngen = info[0]
    nocc = info[1]
    nvir = info[2]
    H1_gg = info[3]
    H1_gc = info[4]
    F1_gg = info[5]
    F1_gc = info[6]
    F1_cc = info[7]
    V2_gg_gg = info[8]
    V2_gg_gc = info[9]
    R2_gg_vc = info[10]
    R2_gg_cc = info[11]
    V_F12_gg_gg = info[12]
    X_F12_gg_gg = info[13]
    B_F12_gg_gg = info[14]
    R1 = info[15]
    R2_gg_oc = info[16]

    # slices !!
    slice_o = slice(0, nocc)
    slice_v = slice(nocc, ngen)

    # Einsum expressions!!
    #  H1_R2  
    H_2body[:, slice_v, :, :] += 0.5 * np.einsum('px,utbx->pbtu', H1_gc[:, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += 0.5 * np.einsum('py,tuay->paut', H1_gc[:, :], R2_gg_vc, optimize=True)
    #  H1_R2D  
    H_2body[:, :, slice_v, :] += 0.5 * np.einsum('tuay,qy->tuaq', R2_gg_vc, H1_gc[:, :], optimize=True)
    H_2body[:, :, :, slice_v] += 0.5 * np.einsum('utbx,qx->tuqb', R2_gg_vc, H1_gc[:, :], optimize=True)
    #  F1_R2_R2  
    #  F1_R2_R2D  
    H_2body[:, slice_v, slice_v, :] += 0.25 * np.einsum('Ttcz,zx,utbx->Tbcu', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.25 * np.einsum('utcz,zx,utbx->bc', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += -0.125 * np.einsum('tUcz,zx,utbx->Ubcu', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.125 * np.einsum('tucz,zx,utbx->bc', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += -0.125 * np.einsum('uUcz,zx,utbx->Ubct', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.125 * np.einsum('utcz,zx,utbx->bc', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += -0.125 * np.einsum('Tucz,zx,utbx->Tbct', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.125 * np.einsum('tucz,zx,utbx->bc', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('tucz,zx,utbx->bc', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('utcz,zx,utbx->bc', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_2body[:, :, slice_v, :] += 0.25 * np.einsum('Tucz,px,tuxz->Tpct', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += -0.5 * np.einsum('Tucz,tx,tuxz->Tc', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += 0.25 * np.einsum('tucz,px,tuxz->pc', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_2body[:, :, slice_v, :] += 0.25 * np.einsum('TUcz,tx,tuxz->TUcu', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += -0.5 * np.einsum('Tucz,tx,tuxz->Tc', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += 0.25 * np.einsum('uUcz,tx,tuxz->Uc', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += 0.5 * np.einsum('Tucz,tx,tuxz->Tc', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += -0.25 * np.einsum('Ttcz,ux,tuxz->Tc', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_2body[:, :, slice_v, :] += -0.125 * np.einsum('uUcz,px,tuxz->Upct', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += 0.25 * np.einsum('uUcz,tx,tuxz->Uc', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += -0.125 * np.einsum('utcz,px,tuxz->pc', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_2body[:, :, slice_v, :] += -0.125 * np.einsum('tUcz,px,tuxz->Upcu', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += 0.25 * np.einsum('tUcz,ux,tuxz->Uc', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += -0.125 * np.einsum('tucz,px,tuxz->pc', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_2body[:, :, slice_v, :] += -0.125 * np.einsum('Ttcz,px,tuxz->Tpcu', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += 0.25 * np.einsum('Ttcz,ux,tuxz->Tc', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += -0.125 * np.einsum('utcz,px,tuxz->pc', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_2body[:, :, slice_v, :] += -0.125 * np.einsum('TUcz,ux,tuxz->TUct', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += 0.25 * np.einsum('Ttcz,ux,tuxz->Tc', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += -0.125 * np.einsum('tUcz,ux,tuxz->Uc', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += -0.25 * np.einsum('uUcz,tx,tuxz->Uc', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += 0.125 * np.einsum('tUcz,ux,tuxz->Uc', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += -0.25 * np.einsum('utcz,px,tuxz->pc', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += 0.125 * np.einsum('tucz,px,tuxz->pc', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.25 * np.einsum('Utdw,wx,utbx->Ubdu', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.25 * np.einsum('utdw,wx,utbx->bd', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, slice_v] += -0.125 * np.einsum('Uudw,wx,utbx->Ubtd', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.25 * np.einsum('tudw,wx,utbx->bd', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += -0.125 * np.einsum('tTdw,wx,utbx->Tbdu', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.125 * np.einsum('tudw,wx,utbx->bd', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, slice_v] += -0.125 * np.einsum('uTdw,wx,utbx->Tbtd', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.25 * np.einsum('utdw,wx,utbx->bd', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('utdw,wx,utbx->bd', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('tudw,wx,utbx->bd', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_2body[:, :, slice_v, :] += 0.25 * np.einsum('Uudw,px,tuxw->Updt', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += -0.5 * np.einsum('Uudw,tx,tuxw->Ud', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += 0.25 * np.einsum('tudw,px,tuxw->pd', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_2body[:, :, :, slice_v] += 0.25 * np.einsum('UTdw,tx,tuxw->TUud', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += -0.5 * np.einsum('Uudw,tx,tuxw->Ud', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += 0.25 * np.einsum('uTdw,tx,tuxw->Td', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += 0.5 * np.einsum('Uudw,tx,tuxw->Ud', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += -0.25 * np.einsum('Utdw,ux,tuxw->Ud', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_2body[:, :, :, slice_v] += -0.125 * np.einsum('Utdw,px,tuxw->Upud', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += 0.25 * np.einsum('utdw,px,tuxw->pd', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += -0.125 * np.einsum('Utdw,ux,tuxw->Ud', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_2body[:, :, slice_v, :] += -0.125 * np.einsum('uTdw,px,tuxw->Tpdt', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += 0.25 * np.einsum('uTdw,tx,tuxw->Td', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += -0.125 * np.einsum('utdw,px,tuxw->pd', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_2body[:, :, :, slice_v] += -0.125 * np.einsum('tTdw,px,tuxw->Tpud', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += 0.25 * np.einsum('tudw,px,tuxw->pd', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += -0.125 * np.einsum('tTdw,ux,tuxw->Td', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_2body[:, :, slice_v, :] += -0.125 * np.einsum('UTdw,ux,tuxw->TUdt', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += 0.25 * np.einsum('tTdw,ux,tuxw->Td', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += -0.125 * np.einsum('Utdw,ux,tuxw->Ud', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += -0.25 * np.einsum('uTdw,tx,tuxw->Td', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += 0.125 * np.einsum('tTdw,ux,tuxw->Td', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += -0.25 * np.einsum('tudw,px,tuxw->pd', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += 0.125 * np.einsum('utdw,px,tuxw->pd', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_2body[:, :, :, :] += 0.0625 * np.einsum('UTtu->UTut', B_F12_gg_gg, optimize=True)
    H_2body[:, :, :, :] += 0.0625 * np.einsum('TUtu->TUtu', B_F12_gg_gg, optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.25 * np.einsum('Tucz,zy,tuay->Tact', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.25 * np.einsum('tucz,zy,tuay->ac', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += -0.125 * np.einsum('uUcz,zy,tuay->Uact', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.125 * np.einsum('utcz,zy,tuay->ac', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += -0.125 * np.einsum('tUcz,zy,tuay->Uacu', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.125 * np.einsum('tucz,zy,tuay->ac', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += -0.125 * np.einsum('Ttcz,zy,tuay->Tacu', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.125 * np.einsum('utcz,zy,tuay->ac', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('utcz,zy,tuay->ac', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('tucz,zy,tuay->ac', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_2body[:, :, slice_v, :] += 0.25 * np.einsum('Ttcz,py,tuzy->Tpcu', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += -0.5 * np.einsum('Ttcz,uy,tuzy->Tc', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += 0.25 * np.einsum('utcz,py,tuzy->pc', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_2body[:, :, slice_v, :] += 0.25 * np.einsum('TUcz,uy,tuzy->TUct', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += -0.5 * np.einsum('Ttcz,uy,tuzy->Tc', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += 0.25 * np.einsum('tUcz,uy,tuzy->Uc', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += 0.5 * np.einsum('Ttcz,uy,tuzy->Tc', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += -0.25 * np.einsum('Tucz,ty,tuzy->Tc', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_2body[:, :, slice_v, :] += -0.125 * np.einsum('tUcz,py,tuzy->Upcu', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += 0.25 * np.einsum('tUcz,uy,tuzy->Uc', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += -0.125 * np.einsum('tucz,py,tuzy->pc', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_2body[:, :, slice_v, :] += -0.125 * np.einsum('uUcz,py,tuzy->Upct', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += 0.25 * np.einsum('uUcz,ty,tuzy->Uc', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += -0.125 * np.einsum('utcz,py,tuzy->pc', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_2body[:, :, slice_v, :] += -0.125 * np.einsum('Tucz,py,tuzy->Tpct', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += 0.25 * np.einsum('Tucz,ty,tuzy->Tc', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += -0.125 * np.einsum('tucz,py,tuzy->pc', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_2body[:, :, slice_v, :] += -0.125 * np.einsum('TUcz,ty,tuzy->TUcu', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += 0.25 * np.einsum('Tucz,ty,tuzy->Tc', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += -0.125 * np.einsum('uUcz,ty,tuzy->Uc', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += -0.25 * np.einsum('tUcz,uy,tuzy->Uc', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += 0.125 * np.einsum('uUcz,ty,tuzy->Uc', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += -0.25 * np.einsum('tucz,py,tuzy->pc', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += 0.125 * np.einsum('utcz,py,tuzy->pc', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.25 * np.einsum('Uudw,wy,tuay->Uadt', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.25 * np.einsum('tudw,wy,tuay->ad', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, slice_v] += -0.125 * np.einsum('Utdw,wy,tuay->Uaud', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.25 * np.einsum('utdw,wy,tuay->ad', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += -0.125 * np.einsum('uTdw,wy,tuay->Tadt', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.125 * np.einsum('utdw,wy,tuay->ad', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, slice_v] += -0.125 * np.einsum('tTdw,wy,tuay->Taud', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.25 * np.einsum('tudw,wy,tuay->ad', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('tudw,wy,tuay->ad', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('utdw,wy,tuay->ad', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_2body[:, :, slice_v, :] += 0.25 * np.einsum('Utdw,py,tuwy->Updu', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += -0.5 * np.einsum('Utdw,uy,tuwy->Ud', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += 0.25 * np.einsum('utdw,py,tuwy->pd', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_2body[:, :, :, slice_v] += 0.25 * np.einsum('UTdw,uy,tuwy->TUtd', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += -0.5 * np.einsum('Utdw,uy,tuwy->Ud', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += 0.25 * np.einsum('tTdw,uy,tuwy->Td', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += 0.5 * np.einsum('Utdw,uy,tuwy->Ud', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += -0.25 * np.einsum('Uudw,ty,tuwy->Ud', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_2body[:, :, :, slice_v] += -0.125 * np.einsum('Uudw,py,tuwy->Uptd', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += 0.25 * np.einsum('tudw,py,tuwy->pd', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += -0.125 * np.einsum('Uudw,ty,tuwy->Ud', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_2body[:, :, slice_v, :] += -0.125 * np.einsum('tTdw,py,tuwy->Tpdu', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += 0.25 * np.einsum('tTdw,uy,tuwy->Td', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += -0.125 * np.einsum('tudw,py,tuwy->pd', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_2body[:, :, :, slice_v] += -0.125 * np.einsum('uTdw,py,tuwy->Tptd', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += 0.25 * np.einsum('utdw,py,tuwy->pd', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += -0.125 * np.einsum('uTdw,ty,tuwy->Td', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_2body[:, :, slice_v, :] += -0.125 * np.einsum('UTdw,ty,tuwy->TUdu', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += 0.25 * np.einsum('uTdw,ty,tuwy->Td', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += -0.125 * np.einsum('Uudw,ty,tuwy->Ud', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += -0.25 * np.einsum('tTdw,uy,tuwy->Td', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += 0.125 * np.einsum('uTdw,ty,tuwy->Td', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += -0.25 * np.einsum('utdw,py,tuwy->pd', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_1body[:, slice_v] += 0.125 * np.einsum('tudw,py,tuwy->pd', R2_gg_vc, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_2body[:, :, :, :] += 0.0625 * np.einsum('UTut->UTut', B_F12_gg_gg, optimize=True)
    H_2body[:, :, :, :] += 0.0625 * np.einsum('TUut->TUtu', B_F12_gg_gg, optimize=True)
    H_2body[:, slice_v, slice_v, :] += -0.25 * np.einsum('Ttcz,utbz,uq->Tbcq', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('qtcz,utbz,uq->bc', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.125 * np.einsum('tUcz,utbz,uq->Ubcq', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('tqcz,utbz,uq->bc', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.125 * np.einsum('qUcz,utbz,uq->Ubct', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('qtcz,utbz,uq->bc', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.125 * np.einsum('Tqcz,utbz,uq->Tbct', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('tqcz,utbz,uq->bc', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += 0.25 * np.einsum('tqcz,utbz,uq->bc', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += -0.125 * np.einsum('qtcz,utbz,uq->bc', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_2body[:, slice_v, slice_v, :] += -0.25 * np.einsum('Tqcz,tuaz,uq->Tact', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('tqcz,tuaz,uq->ac', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.125 * np.einsum('qUcz,tuaz,uq->Uact', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('qtcz,tuaz,uq->ac', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.125 * np.einsum('tUcz,tuaz,uq->Uacq', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('tqcz,tuaz,uq->ac', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.125 * np.einsum('Ttcz,tuaz,uq->Tacq', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('qtcz,tuaz,uq->ac', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += 0.25 * np.einsum('qtcz,tuaz,uq->ac', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += -0.125 * np.einsum('tqcz,tuaz,uq->ac', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_2body[:, slice_v, slice_v, :] += -0.25 * np.einsum('Utdw,utbw,uq->Ubdq', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('qtdw,utbw,uq->bd', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_2body[:, slice_v, :, slice_v] += 0.125 * np.einsum('Uqdw,utbw,uq->Ubtd', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('tqdw,utbw,uq->bd', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.125 * np.einsum('tTdw,utbw,uq->Tbdq', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('tqdw,utbw,uq->bd', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_2body[:, slice_v, :, slice_v] += 0.125 * np.einsum('qTdw,utbw,uq->Tbtd', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('qtdw,utbw,uq->bd', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += 0.25 * np.einsum('qtdw,utbw,uq->bd', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += -0.125 * np.einsum('tqdw,utbw,uq->bd', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_2body[:, slice_v, slice_v, :] += -0.25 * np.einsum('Uqdw,tuaw,uq->Uadt', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('tqdw,tuaw,uq->ad', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_2body[:, slice_v, :, slice_v] += 0.125 * np.einsum('Utdw,tuaw,uq->Uaqd', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('qtdw,tuaw,uq->ad', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.125 * np.einsum('qTdw,tuaw,uq->Tadt', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('qtdw,tuaw,uq->ad', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_2body[:, slice_v, :, slice_v] += 0.125 * np.einsum('tTdw,tuaw,uq->Taqd', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('tqdw,tuaw,uq->ad', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += 0.25 * np.einsum('tqdw,tuaw,uq->ad', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += -0.125 * np.einsum('qtdw,tuaw,uq->ad', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_2body[:, :, :, :] += -0.125 * np.einsum('uq,TUut->TUqt', F1_gg[:, :], X_F12_gg_gg, optimize=True)
    H_2body[:, :, :, :] += -0.125 * np.einsum('uq,TUtu->TUtq', F1_gg[:, :], X_F12_gg_gg, optimize=True)
    H_2body[:, slice_v, slice_v, :] += -0.25 * np.einsum('Tqcz,utbz,tq->Tbcu', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('uqcz,utbz,tq->bc', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.125 * np.einsum('qUcz,utbz,tq->Ubcu', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('qucz,utbz,tq->bc', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.125 * np.einsum('uUcz,utbz,tq->Ubcq', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('uqcz,utbz,tq->bc', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.125 * np.einsum('Tucz,utbz,tq->Tbcq', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('qucz,utbz,tq->bc', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += 0.25 * np.einsum('qucz,utbz,tq->bc', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += -0.125 * np.einsum('uqcz,utbz,tq->bc', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_2body[:, slice_v, slice_v, :] += -0.25 * np.einsum('Tucz,tuaz,tq->Tacq', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('qucz,tuaz,tq->ac', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.125 * np.einsum('uUcz,tuaz,tq->Uacq', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('uqcz,tuaz,tq->ac', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.125 * np.einsum('qUcz,tuaz,tq->Uacu', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('qucz,tuaz,tq->ac', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.125 * np.einsum('Tqcz,tuaz,tq->Tacu', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('uqcz,tuaz,tq->ac', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += 0.25 * np.einsum('uqcz,tuaz,tq->ac', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += -0.125 * np.einsum('qucz,tuaz,tq->ac', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_2body[:, slice_v, slice_v, :] += -0.25 * np.einsum('Uqdw,utbw,tq->Ubdu', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('uqdw,utbw,tq->bd', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_2body[:, slice_v, :, slice_v] += 0.125 * np.einsum('Uudw,utbw,tq->Ubqd', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('qudw,utbw,tq->bd', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.125 * np.einsum('qTdw,utbw,tq->Tbdu', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('qudw,utbw,tq->bd', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_2body[:, slice_v, :, slice_v] += 0.125 * np.einsum('uTdw,utbw,tq->Tbqd', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('uqdw,utbw,tq->bd', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += 0.25 * np.einsum('uqdw,utbw,tq->bd', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += -0.125 * np.einsum('qudw,utbw,tq->bd', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_2body[:, slice_v, slice_v, :] += -0.25 * np.einsum('Uudw,tuaw,tq->Uadq', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('qudw,tuaw,tq->ad', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_2body[:, slice_v, :, slice_v] += 0.125 * np.einsum('Uqdw,tuaw,tq->Uaud', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('uqdw,tuaw,tq->ad', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.125 * np.einsum('uTdw,tuaw,tq->Tadq', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('uqdw,tuaw,tq->ad', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_2body[:, slice_v, :, slice_v] += 0.125 * np.einsum('qTdw,tuaw,tq->Taud', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('qudw,tuaw,tq->ad', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += 0.25 * np.einsum('qudw,tuaw,tq->ad', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_1body[slice_v, slice_v] += -0.125 * np.einsum('uqdw,tuaw,tq->ad', R2_gg_vc, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_2body[:, :, :, :] += -0.125 * np.einsum('tq,TUut->TUuq', F1_gg[:, :], X_F12_gg_gg, optimize=True)
    H_2body[:, :, :, :] += -0.125 * np.einsum('tq,TUtu->TUqu', F1_gg[:, :], X_F12_gg_gg, optimize=True)
    #  F1_R2D_R2  
    H_2body[:, slice_v, slice_v, :] += -0.25 * np.einsum('pq,qTay,UTdy->pdaU', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('Uq,qTay,UTdy->da', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.125 * np.einsum('Tq,quay,UTdy->udaU', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('Tq,qUay,UTdy->da', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.125 * np.einsum('Uq,quay,UTdy->udaT', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('Uq,qTay,UTdy->da', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.125 * np.einsum('pq,qUay,UTdy->pdaT', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('Tq,qUay,UTdy->da', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.25 * np.einsum('Tq,qUay,UTdy->da', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.125 * np.einsum('Uq,qTay,UTdy->da', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += -0.25 * np.einsum('pq,qUay,TUcy->pcaT', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('Tq,qUay,TUcy->ca', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.125 * np.einsum('Uq,quay,TUcy->ucaT', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('Uq,qTay,TUcy->ca', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.125 * np.einsum('Tq,quay,TUcy->ucaU', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('Tq,qUay,TUcy->ca', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.125 * np.einsum('pq,qTay,TUcy->pcaU', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('Uq,qTay,TUcy->ca', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.25 * np.einsum('Uq,qTay,TUcy->ca', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.125 * np.einsum('Tq,qUay,TUcy->ca', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += -0.25 * np.einsum('Tq,uqbx,UTdx->udbU', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('Tq,Uqbx,UTdx->db', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, slice_v] += 0.125 * np.einsum('Uq,uqbx,UTdx->udTb', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('Uq,Tqbx,UTdx->db', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.125 * np.einsum('pq,Tqbx,UTdx->pdbU', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('Uq,Tqbx,UTdx->db', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, slice_v] += 0.125 * np.einsum('pq,Uqbx,UTdx->pdTb', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('Tq,Uqbx,UTdx->db', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.25 * np.einsum('Tq,Uqbx,UTdx->db', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.125 * np.einsum('Uq,Tqbx,UTdx->db', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += -0.25 * np.einsum('Uq,uqbx,TUcx->ucbT', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('Uq,Tqbx,TUcx->cb', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, slice_v] += 0.125 * np.einsum('Tq,uqbx,TUcx->ucUb', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('Tq,Uqbx,TUcx->cb', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.125 * np.einsum('pq,Uqbx,TUcx->pcbT', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('Tq,Uqbx,TUcx->cb', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, slice_v] += 0.125 * np.einsum('pq,Tqbx,TUcx->pcUb', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('Uq,Tqbx,TUcx->cb', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.25 * np.einsum('Uq,Tqbx,TUcx->cb', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.125 * np.einsum('Tq,Uqbx,TUcx->cb', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_2body[:, :, :, :] += -0.125 * np.einsum('pq,quUT->puUT', F1_gg[:, :], X_F12_gg_gg, optimize=True)
    H_2body[:, :, :, :] += -0.125 * np.einsum('pq,quTU->puTU', F1_gg[:, :], X_F12_gg_gg, optimize=True)
    H_2body[:, slice_v, slice_v, :] += -0.25 * np.einsum('pq,qTbx,UTdx->pdbU', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('Uq,qTbx,UTdx->db', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.125 * np.einsum('Tq,qtbx,UTdx->tdbU', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('Tq,qUbx,UTdx->db', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.125 * np.einsum('Uq,qtbx,UTdx->tdbT', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('Uq,qTbx,UTdx->db', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.125 * np.einsum('pq,qUbx,UTdx->pdbT', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('Tq,qUbx,UTdx->db', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.25 * np.einsum('Tq,qUbx,UTdx->db', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.125 * np.einsum('Uq,qTbx,UTdx->db', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += -0.25 * np.einsum('pq,qUbx,TUcx->pcbT', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('Tq,qUbx,TUcx->cb', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.125 * np.einsum('Uq,qtbx,TUcx->tcbT', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('Uq,qTbx,TUcx->cb', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.125 * np.einsum('Tq,qtbx,TUcx->tcbU', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('Tq,qUbx,TUcx->cb', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.125 * np.einsum('pq,qTbx,TUcx->pcbU', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('Uq,qTbx,TUcx->cb', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.25 * np.einsum('Uq,qTbx,TUcx->cb', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.125 * np.einsum('Tq,qUbx,TUcx->cb', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += -0.25 * np.einsum('Tq,tqay,UTdy->tdaU', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('Tq,Uqay,UTdy->da', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, slice_v] += 0.125 * np.einsum('Uq,tqay,UTdy->tdTa', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('Uq,Tqay,UTdy->da', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.125 * np.einsum('pq,Tqay,UTdy->pdaU', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('Uq,Tqay,UTdy->da', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, slice_v] += 0.125 * np.einsum('pq,Uqay,UTdy->pdTa', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('Tq,Uqay,UTdy->da', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.25 * np.einsum('Tq,Uqay,UTdy->da', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.125 * np.einsum('Uq,Tqay,UTdy->da', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += -0.25 * np.einsum('Uq,tqay,TUcy->tcaT', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('Uq,Tqay,TUcy->ca', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, slice_v] += 0.125 * np.einsum('Tq,tqay,TUcy->tcUa', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('Tq,Uqay,TUcy->ca', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.125 * np.einsum('pq,Uqay,TUcy->pcaT', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('Tq,Uqay,TUcy->ca', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, slice_v] += 0.125 * np.einsum('pq,Tqay,TUcy->pcUa', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('Uq,Tqay,TUcy->ca', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.25 * np.einsum('Uq,Tqay,TUcy->ca', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.125 * np.einsum('Tq,Uqay,TUcy->ca', F1_gg[:, :], R2_gg_vc, R2_gg_vc, optimize=True)
    H_2body[:, :, :, :] += -0.125 * np.einsum('pq,tqTU->ptUT', F1_gg[:, :], X_F12_gg_gg, optimize=True)
    H_2body[:, :, :, :] += -0.125 * np.einsum('pq,tqUT->ptTU', F1_gg[:, :], X_F12_gg_gg, optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.25 * np.einsum('tTay,yw,UTdw->tdaU', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.25 * np.einsum('UTay,yw,UTdw->da', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += -0.125 * np.einsum('Tuay,yw,UTdw->udaU', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.125 * np.einsum('TUay,yw,UTdw->da', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += -0.125 * np.einsum('Uuay,yw,UTdw->udaT', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.125 * np.einsum('UTay,yw,UTdw->da', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += -0.125 * np.einsum('tUay,yw,UTdw->tdaT', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.125 * np.einsum('TUay,yw,UTdw->da', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('TUay,yw,UTdw->da', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('UTay,yw,UTdw->da', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.25 * np.einsum('tUay,yz,TUcz->tcaT', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.25 * np.einsum('TUay,yz,TUcz->ca', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += -0.125 * np.einsum('Uuay,yz,TUcz->ucaT', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.125 * np.einsum('UTay,yz,TUcz->ca', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += -0.125 * np.einsum('Tuay,yz,TUcz->ucaU', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.125 * np.einsum('TUay,yz,TUcz->ca', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += -0.125 * np.einsum('tTay,yz,TUcz->tcaU', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.125 * np.einsum('UTay,yz,TUcz->ca', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('UTay,yz,TUcz->ca', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('TUay,yz,TUcz->ca', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += 0.25 * np.einsum('Tuxy,qy,UTdx->udqU', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.5 * np.einsum('Tqxy,qy,UTdx->dU', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.25 * np.einsum('TUxy,qy,UTdx->dq', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += 0.25 * np.einsum('tqxy,qy,UTdx->tdTU', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.5 * np.einsum('Tqxy,qy,UTdx->dU', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.25 * np.einsum('Uqxy,qy,UTdx->dT', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.5 * np.einsum('Tqxy,qy,UTdx->dU', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.25 * np.einsum('qTxy,qy,UTdx->dU', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += -0.125 * np.einsum('quxy,qy,UTdx->udTU', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.25 * np.einsum('qTxy,qy,UTdx->dU', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.125 * np.einsum('qUxy,qy,UTdx->dT', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += -0.125 * np.einsum('Uuxy,qy,UTdx->udTq', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.25 * np.einsum('UTxy,qy,UTdx->dq', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.125 * np.einsum('Uqxy,qy,UTdx->dT', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += -0.125 * np.einsum('tTxy,qy,UTdx->tdqU', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.25 * np.einsum('qTxy,qy,UTdx->dU', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.125 * np.einsum('UTxy,qy,UTdx->dq', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += -0.125 * np.einsum('tUxy,qy,UTdx->tdTq', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.25 * np.einsum('TUxy,qy,UTdx->dq', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.125 * np.einsum('qUxy,qy,UTdx->dT', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.25 * np.einsum('qUxy,qy,UTdx->dT', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.125 * np.einsum('Uqxy,qy,UTdx->dT', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.25 * np.einsum('TUxy,qy,UTdx->dq', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.125 * np.einsum('UTxy,qy,UTdx->dq', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += 0.25 * np.einsum('Uuxy,qy,TUcx->ucqT', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.5 * np.einsum('Uqxy,qy,TUcx->cT', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.25 * np.einsum('UTxy,qy,TUcx->cq', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += 0.25 * np.einsum('tqxy,qy,TUcx->tcUT', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.5 * np.einsum('Uqxy,qy,TUcx->cT', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.25 * np.einsum('Tqxy,qy,TUcx->cU', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.5 * np.einsum('Uqxy,qy,TUcx->cT', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.25 * np.einsum('qUxy,qy,TUcx->cT', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += -0.125 * np.einsum('quxy,qy,TUcx->ucUT', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.25 * np.einsum('qUxy,qy,TUcx->cT', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.125 * np.einsum('qTxy,qy,TUcx->cU', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += -0.125 * np.einsum('Tuxy,qy,TUcx->ucUq', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.25 * np.einsum('TUxy,qy,TUcx->cq', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.125 * np.einsum('Tqxy,qy,TUcx->cU', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += -0.125 * np.einsum('tUxy,qy,TUcx->tcqT', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.25 * np.einsum('qUxy,qy,TUcx->cT', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.125 * np.einsum('TUxy,qy,TUcx->cq', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += -0.125 * np.einsum('tTxy,qy,TUcx->tcUq', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.25 * np.einsum('UTxy,qy,TUcx->cq', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.125 * np.einsum('qTxy,qy,TUcx->cU', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.25 * np.einsum('qTxy,qy,TUcx->cU', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.125 * np.einsum('Tqxy,qy,TUcx->cU', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.25 * np.einsum('UTxy,qy,TUcx->cq', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.125 * np.einsum('TUxy,qy,TUcx->cq', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_2body[:, :, :, :] += 0.0625 * np.einsum('utTU->utUT', B_F12_gg_gg, optimize=True)
    H_2body[:, :, :, :] += 0.0625 * np.einsum('utUT->utUT', B_F12_gg_gg, optimize=True)
    H_2body[:, slice_v, :, :] += 0.25 * np.einsum('quxy,qx,UTdy->udTU', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.5 * np.einsum('qTxy,qx,UTdy->dU', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.25 * np.einsum('qUxy,qx,UTdy->dT', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += 0.25 * np.einsum('tTxy,qx,UTdy->tdqU', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.5 * np.einsum('qTxy,qx,UTdy->dU', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.25 * np.einsum('UTxy,qx,UTdy->dq', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.5 * np.einsum('qTxy,qx,UTdy->dU', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.25 * np.einsum('Tqxy,qx,UTdy->dU', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += -0.125 * np.einsum('Tuxy,qx,UTdy->udqU', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.25 * np.einsum('Tqxy,qx,UTdy->dU', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.125 * np.einsum('TUxy,qx,UTdy->dq', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += -0.125 * np.einsum('Uuxy,qx,UTdy->udqT', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.25 * np.einsum('Uqxy,qx,UTdy->dT', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.125 * np.einsum('UTxy,qx,UTdy->dq', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += -0.125 * np.einsum('tqxy,qx,UTdy->tdTU', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.25 * np.einsum('Tqxy,qx,UTdy->dU', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.125 * np.einsum('Uqxy,qx,UTdy->dT', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += -0.125 * np.einsum('tUxy,qx,UTdy->tdqT', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.25 * np.einsum('qUxy,qx,UTdy->dT', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.125 * np.einsum('TUxy,qx,UTdy->dq', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.25 * np.einsum('TUxy,qx,UTdy->dq', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.125 * np.einsum('UTxy,qx,UTdy->dq', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.25 * np.einsum('qUxy,qx,UTdy->dT', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.125 * np.einsum('Uqxy,qx,UTdy->dT', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += 0.25 * np.einsum('quxy,qx,TUcy->ucUT', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.5 * np.einsum('qUxy,qx,TUcy->cT', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.25 * np.einsum('qTxy,qx,TUcy->cU', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += 0.25 * np.einsum('tUxy,qx,TUcy->tcqT', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.5 * np.einsum('qUxy,qx,TUcy->cT', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.25 * np.einsum('TUxy,qx,TUcy->cq', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.5 * np.einsum('qUxy,qx,TUcy->cT', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.25 * np.einsum('Uqxy,qx,TUcy->cT', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += -0.125 * np.einsum('Uuxy,qx,TUcy->ucqT', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.25 * np.einsum('Uqxy,qx,TUcy->cT', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.125 * np.einsum('UTxy,qx,TUcy->cq', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += -0.125 * np.einsum('Tuxy,qx,TUcy->ucqU', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.25 * np.einsum('Tqxy,qx,TUcy->cU', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.125 * np.einsum('TUxy,qx,TUcy->cq', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += -0.125 * np.einsum('tqxy,qx,TUcy->tcUT', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.25 * np.einsum('Uqxy,qx,TUcy->cT', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.125 * np.einsum('Tqxy,qx,TUcy->cU', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += -0.125 * np.einsum('tTxy,qx,TUcy->tcqU', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.25 * np.einsum('qTxy,qx,TUcy->cU', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.125 * np.einsum('UTxy,qx,TUcy->cq', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.25 * np.einsum('UTxy,qx,TUcy->cq', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.125 * np.einsum('TUxy,qx,TUcy->cq', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.25 * np.einsum('qTxy,qx,TUcy->cU', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.125 * np.einsum('Tqxy,qx,TUcy->cU', R2_gg_cc, F1_gc[:, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.25 * np.einsum('uTbx,xw,UTdw->udbU', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.25 * np.einsum('UTbx,xw,UTdw->db', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, slice_v] += -0.125 * np.einsum('uUbx,xw,UTdw->udTb', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.25 * np.einsum('TUbx,xw,UTdw->db', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += -0.125 * np.einsum('Ttbx,xw,UTdw->tdbU', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.125 * np.einsum('TUbx,xw,UTdw->db', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, slice_v] += -0.125 * np.einsum('Utbx,xw,UTdw->tdTb', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.25 * np.einsum('UTbx,xw,UTdw->db', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('UTbx,xw,UTdw->db', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('TUbx,xw,UTdw->db', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += 0.25 * np.einsum('uUbx,xz,TUcz->ucbT', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.25 * np.einsum('TUbx,xz,TUcz->cb', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, slice_v] += -0.125 * np.einsum('uTbx,xz,TUcz->ucUb', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.25 * np.einsum('UTbx,xz,TUcz->cb', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, slice_v, :] += -0.125 * np.einsum('Utbx,xz,TUcz->tcbT', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.125 * np.einsum('UTbx,xz,TUcz->cb', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, slice_v] += -0.125 * np.einsum('Ttbx,xz,TUcz->tcUb', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.25 * np.einsum('TUbx,xz,TUcz->cb', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += -0.25 * np.einsum('TUbx,xz,TUcz->cb', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_1body[slice_v, slice_v] += 0.125 * np.einsum('UTbx,xz,TUcz->cb', R2_gg_vc, F1_cc, R2_gg_vc, optimize=True)
    H_2body[:, :, :, :] += 0.0625 * np.einsum('tuUT->tuTU', B_F12_gg_gg, optimize=True)
    H_2body[:, :, :, :] += 0.0625 * np.einsum('tuTU->tuTU', B_F12_gg_gg, optimize=True)
    #  F1_R2D_R2D  
    #  V2_R2  
    H_2body[:, slice_v, :, :] += 0.5 * np.einsum('rqrx,utbx->qbtu', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -1.0 * np.einsum('rtrx,utbx->bu', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.5 * np.einsum('rurx,utbx->bt', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += 0.5 * np.einsum('ptrx,utbx->pbru', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -1.0 * np.einsum('rtrx,utbx->bu', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.5 * np.einsum('utrx,utbx->br', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 1.0 * np.einsum('rtrx,utbx->bu', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.5 * np.einsum('trrx,utbx->bu', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += -0.25 * np.einsum('tqrx,utbx->qbru', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.5 * np.einsum('trrx,utbx->bu', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.25 * np.einsum('turx,utbx->br', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += -0.25 * np.einsum('uqrx,utbx->qbrt', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.5 * np.einsum('urrx,utbx->bt', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.25 * np.einsum('utrx,utbx->br', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += -0.25 * np.einsum('prrx,utbx->pbtu', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.5 * np.einsum('trrx,utbx->bu', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.25 * np.einsum('urrx,utbx->bt', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += -0.25 * np.einsum('purx,utbx->pbrt', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.5 * np.einsum('rurx,utbx->bt', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.25 * np.einsum('turx,utbx->br', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.5 * np.einsum('turx,utbx->br', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.25 * np.einsum('utrx,utbx->br', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.5 * np.einsum('rurx,utbx->bt', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.25 * np.einsum('urrx,utbx->bt', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += 0.5 * np.einsum('rqry,tuay->qaut', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -1.0 * np.einsum('rury,tuay->at', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.5 * np.einsum('rtry,tuay->au', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += 0.5 * np.einsum('pury,tuay->part', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -1.0 * np.einsum('rury,tuay->at', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.5 * np.einsum('tury,tuay->ar', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 1.0 * np.einsum('rury,tuay->at', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.5 * np.einsum('urry,tuay->at', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += -0.25 * np.einsum('uqry,tuay->qart', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.5 * np.einsum('urry,tuay->at', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.25 * np.einsum('utry,tuay->ar', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += -0.25 * np.einsum('tqry,tuay->qaru', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.5 * np.einsum('trry,tuay->au', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.25 * np.einsum('tury,tuay->ar', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += -0.25 * np.einsum('prry,tuay->paut', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.5 * np.einsum('urry,tuay->at', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.25 * np.einsum('trry,tuay->au', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += -0.25 * np.einsum('ptry,tuay->paru', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.5 * np.einsum('rtry,tuay->au', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.25 * np.einsum('utry,tuay->ar', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.5 * np.einsum('utry,tuay->ar', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.25 * np.einsum('tury,tuay->ar', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.5 * np.einsum('rtry,tuay->au', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.25 * np.einsum('trry,tuay->au', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += 0.5 * np.einsum('qtsx,utbx->qbsu', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -1.0 * np.einsum('stsx,utbx->bu', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.5 * np.einsum('utsx,utbx->bs', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += 0.5 * np.einsum('spsx,utbx->pbtu', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -1.0 * np.einsum('stsx,utbx->bu', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.5 * np.einsum('susx,utbx->bt', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 1.0 * np.einsum('stsx,utbx->bu', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.5 * np.einsum('tssx,utbx->bu', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += -0.25 * np.einsum('qssx,utbx->qbtu', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.5 * np.einsum('tssx,utbx->bu', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.25 * np.einsum('ussx,utbx->bt', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += -0.25 * np.einsum('qusx,utbx->qbts', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.5 * np.einsum('tusx,utbx->bs', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.25 * np.einsum('susx,utbx->bt', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += -0.25 * np.einsum('tpsx,utbx->pbsu', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.5 * np.einsum('tssx,utbx->bu', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.25 * np.einsum('tusx,utbx->bs', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += -0.25 * np.einsum('upsx,utbx->pbts', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.5 * np.einsum('utsx,utbx->bs', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.25 * np.einsum('ussx,utbx->bt', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.5 * np.einsum('ussx,utbx->bt', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.25 * np.einsum('susx,utbx->bt', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.5 * np.einsum('utsx,utbx->bs', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.25 * np.einsum('tusx,utbx->bs', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += 0.5 * np.einsum('qusy,tuay->qast', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -1.0 * np.einsum('susy,tuay->at', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.5 * np.einsum('tusy,tuay->as', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += 0.5 * np.einsum('spsy,tuay->paut', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -1.0 * np.einsum('susy,tuay->at', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.5 * np.einsum('stsy,tuay->au', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 1.0 * np.einsum('susy,tuay->at', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.5 * np.einsum('ussy,tuay->at', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += -0.25 * np.einsum('qssy,tuay->qaut', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.5 * np.einsum('ussy,tuay->at', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.25 * np.einsum('tssy,tuay->au', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += -0.25 * np.einsum('qtsy,tuay->qaus', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.5 * np.einsum('utsy,tuay->as', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.25 * np.einsum('stsy,tuay->au', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += -0.25 * np.einsum('upsy,tuay->past', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.5 * np.einsum('ussy,tuay->at', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.25 * np.einsum('utsy,tuay->as', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += -0.25 * np.einsum('tpsy,tuay->paus', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.5 * np.einsum('tusy,tuay->as', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.25 * np.einsum('tssy,tuay->au', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.5 * np.einsum('tssy,tuay->au', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.25 * np.einsum('stsy,tuay->au', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += -0.5 * np.einsum('tusy,tuay->as', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_1body[slice_v, :] += 0.25 * np.einsum('utsy,tuay->as', V2_gg_gc[:, :, :, :], R2_gg_vc, optimize=True)
    H_2body[:, :, :, :] += 0.25 * np.einsum('qptu->pqut', V_F12_gg_gg[:, :, :, :], optimize=True)
    H_2body[:, :, :, :] += 0.25 * np.einsum('pqtu->pqtu', V_F12_gg_gg[:, :, :, :], optimize=True)
    #  V2_R2D  
    H_2body[:, :, slice_v, :] += 0.5 * np.einsum('tray,srqy->tqas', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += -1.0 * np.einsum('tray,srsy->ta', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += 0.5 * np.einsum('sray,srqy->qa', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_2body[:, :, slice_v, :] += 0.5 * np.einsum('tuay,srsy->tuar', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += -1.0 * np.einsum('tray,srsy->ta', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += 0.5 * np.einsum('ruay,srsy->ua', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += 1.0 * np.einsum('tray,srsy->ta', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += -0.5 * np.einsum('tsay,srry->ta', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_2body[:, :, slice_v, :] += -0.25 * np.einsum('ruay,srqy->uqas', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += 0.5 * np.einsum('ruay,srsy->ua', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += -0.25 * np.einsum('rsay,srqy->qa', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_2body[:, :, slice_v, :] += -0.25 * np.einsum('suay,srqy->uqar', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += 0.5 * np.einsum('suay,srry->ua', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += -0.25 * np.einsum('sray,srqy->qa', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_2body[:, :, slice_v, :] += -0.25 * np.einsum('tsay,srqy->tqar', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += 0.5 * np.einsum('tsay,srry->ta', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += -0.25 * np.einsum('rsay,srqy->qa', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_2body[:, :, slice_v, :] += -0.25 * np.einsum('tuay,srry->tuas', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += 0.5 * np.einsum('tsay,srry->ta', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += -0.25 * np.einsum('suay,srry->ua', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += -0.5 * np.einsum('ruay,srsy->ua', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += 0.25 * np.einsum('suay,srry->ua', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += -0.5 * np.einsum('rsay,srqy->qa', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += 0.25 * np.einsum('sray,srqy->qa', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_2body[:, :, slice_v, :] += 0.5 * np.einsum('tsay,rspy->tpar', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += -1.0 * np.einsum('tsay,rsry->ta', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += 0.5 * np.einsum('rsay,rspy->pa', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_2body[:, :, slice_v, :] += 0.5 * np.einsum('tuay,rsry->tuas', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += -1.0 * np.einsum('tsay,rsry->ta', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += 0.5 * np.einsum('suay,rsry->ua', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += 1.0 * np.einsum('tsay,rsry->ta', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += -0.5 * np.einsum('tray,rssy->ta', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_2body[:, :, slice_v, :] += -0.25 * np.einsum('suay,rspy->upar', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += 0.5 * np.einsum('suay,rsry->ua', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += -0.25 * np.einsum('sray,rspy->pa', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_2body[:, :, slice_v, :] += -0.25 * np.einsum('ruay,rspy->upas', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += 0.5 * np.einsum('ruay,rssy->ua', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += -0.25 * np.einsum('rsay,rspy->pa', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_2body[:, :, slice_v, :] += -0.25 * np.einsum('tray,rspy->tpas', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += 0.5 * np.einsum('tray,rssy->ta', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += -0.25 * np.einsum('sray,rspy->pa', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_2body[:, :, slice_v, :] += -0.25 * np.einsum('tuay,rssy->tuar', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += 0.5 * np.einsum('tray,rssy->ta', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += -0.25 * np.einsum('ruay,rssy->ua', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += -0.5 * np.einsum('suay,rsry->ua', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += 0.25 * np.einsum('ruay,rssy->ua', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += -0.5 * np.einsum('sray,rspy->pa', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += 0.25 * np.einsum('rsay,rspy->pa', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_2body[:, :, slice_v, :] += 0.5 * np.einsum('urbx,srqx->uqbs', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += -1.0 * np.einsum('urbx,srsx->ub', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += 0.5 * np.einsum('srbx,srqx->qb', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_2body[:, :, :, slice_v] += 0.5 * np.einsum('utbx,srsx->turb', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += -1.0 * np.einsum('urbx,srsx->ub', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += 0.5 * np.einsum('rtbx,srsx->tb', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += 1.0 * np.einsum('urbx,srsx->ub', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += -0.5 * np.einsum('usbx,srrx->ub', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_2body[:, :, :, slice_v] += -0.25 * np.einsum('usbx,srqx->uqrb', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += 0.5 * np.einsum('rsbx,srqx->qb', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += -0.25 * np.einsum('usbx,srrx->ub', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_2body[:, :, slice_v, :] += -0.25 * np.einsum('rtbx,srqx->tqbs', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += 0.5 * np.einsum('rtbx,srsx->tb', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += -0.25 * np.einsum('rsbx,srqx->qb', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_2body[:, :, :, slice_v] += -0.25 * np.einsum('stbx,srqx->tqrb', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += 0.5 * np.einsum('srbx,srqx->qb', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += -0.25 * np.einsum('stbx,srrx->tb', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_2body[:, :, slice_v, :] += -0.25 * np.einsum('utbx,srrx->tubs', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += 0.5 * np.einsum('stbx,srrx->tb', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += -0.25 * np.einsum('usbx,srrx->ub', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += -0.5 * np.einsum('rtbx,srsx->tb', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += 0.25 * np.einsum('stbx,srrx->tb', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += -0.5 * np.einsum('srbx,srqx->qb', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += 0.25 * np.einsum('rsbx,srqx->qb', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_2body[:, :, slice_v, :] += 0.5 * np.einsum('usbx,rspx->upbr', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += -1.0 * np.einsum('usbx,rsrx->ub', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += 0.5 * np.einsum('rsbx,rspx->pb', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_2body[:, :, :, slice_v] += 0.5 * np.einsum('utbx,rsrx->tusb', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += -1.0 * np.einsum('usbx,rsrx->ub', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += 0.5 * np.einsum('stbx,rsrx->tb', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += 1.0 * np.einsum('usbx,rsrx->ub', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += -0.5 * np.einsum('urbx,rssx->ub', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_2body[:, :, :, slice_v] += -0.25 * np.einsum('urbx,rspx->upsb', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += 0.5 * np.einsum('srbx,rspx->pb', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += -0.25 * np.einsum('urbx,rssx->ub', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_2body[:, :, slice_v, :] += -0.25 * np.einsum('stbx,rspx->tpbr', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += 0.5 * np.einsum('stbx,rsrx->tb', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += -0.25 * np.einsum('srbx,rspx->pb', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_2body[:, :, :, slice_v] += -0.25 * np.einsum('rtbx,rspx->tpsb', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += 0.5 * np.einsum('rsbx,rspx->pb', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += -0.25 * np.einsum('rtbx,rssx->tb', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_2body[:, :, slice_v, :] += -0.25 * np.einsum('utbx,rssx->tubr', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += 0.5 * np.einsum('rtbx,rssx->tb', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += -0.25 * np.einsum('urbx,rssx->ub', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += -0.5 * np.einsum('stbx,rsrx->tb', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += 0.25 * np.einsum('rtbx,rssx->tb', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += -0.5 * np.einsum('rsbx,rspx->pb', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_1body[:, slice_v] += 0.25 * np.einsum('srbx,rspx->pb', R2_gg_vc, V2_gg_gc[:, :, :, :], optimize=True)
    H_2body[:, :, :, :] += 0.25 * np.einsum('tusr->tusr', V_F12_gg_gg[:, :, :, :], optimize=True)
    H_2body[:, :, :, :] += 0.25 * np.einsum('turs->turs', V_F12_gg_gg[:, :, :, :], optimize=True)
    #  H1_R1  
    H_1body[:, :] += 1.0 * np.einsum('pX,PX->pP', H1_gc[:, :], R1, optimize=True)
    #  H1_R1D  
    H_1body[:, :] += 1.0 * np.einsum('PX,qX->Pq', R1, H1_gc[:, :], optimize=True)
    #  V2_R1  
    H_2body[:, :, :, :] += 0.5 * np.einsum('pqrX,PX->pqrP', V2_gg_gc[:, :, :, :], R1, optimize=True)
    H_2body[:, :, :, :] += 0.5 * np.einsum('qpsX,PX->pqPs', V2_gg_gc[:, :, :, :], R1, optimize=True)
    #  V2_R1D  
    H_2body[:, :, :, :] += 0.5 * np.einsum('PX,srqX->Pqrs', R1, V2_gg_gc[:, :, :, :], optimize=True)
    H_2body[:, :, :, :] += 0.5 * np.einsum('PX,rspX->Ppsr', R1, V2_gg_gc[:, :, :, :], optimize=True)
    #  F1_R1_R1  
    #  F1_R1_R1D  
    H_1body[:, :] += 0.5 * np.einsum('QY,YX,PX->QP', R1, F1_cc, R1, optimize=True)
    H_1body[:, :] += -0.5 * np.einsum('QY,PY,Pq->Qq', R1, R1, F1_gg[:, :], optimize=True)
    #  F1_R1D_R1  
    H_1body[:, :] += -0.5 * np.einsum('pq,qX,QX->pQ', F1_gg[:, :], R1, R1, optimize=True)
    H_1body[:, :] += 0.5 * np.einsum('PX,XY,QY->PQ', R1, F1_cc, R1, optimize=True)
    #  F1_R1D_R1D  
    #  F1_R1_R2  
    #  F1_R1_R2D  
    H_2body[:, :, slice_v, :] += 0.25 * np.einsum('tuay,yX,PX->tuaP', R2_gg_vc, F1_cc, R1, optimize=True)
    H_2body[:, :, :, slice_v] += 0.25 * np.einsum('utbx,xX,PX->tuPb', R2_gg_vc, F1_cc, R1, optimize=True)
    H_2body[:, :, slice_v, :] += -0.25 * np.einsum('tuay,Py,Pq->tuaq', R2_gg_vc, R1, F1_gg[:, :], optimize=True)
    H_2body[:, :, :, slice_v] += -0.25 * np.einsum('utbx,Px,Pq->tuqb', R2_gg_vc, R1, F1_gg[:, :], optimize=True)
    #  F1_R1D_R2  
    H_2body[:, slice_v, :, :] += -0.25 * np.einsum('pq,qX,utbX->pbtu', F1_gg[:, :], R1, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += -0.25 * np.einsum('pq,qX,tuaX->paut', F1_gg[:, :], R1, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += 0.25 * np.einsum('PX,Xx,utbx->Pbtu', R1, F1_cc, R2_gg_vc, optimize=True)
    H_2body[:, slice_v, :, :] += 0.25 * np.einsum('PX,Xy,tuay->Paut', R1, F1_cc, R2_gg_vc, optimize=True)
    #  F1_R1D_R2D  
    #  F1_R2_R1  
    #  F1_R2_R1D  
    H_2body[:, slice_v, :, :] += 0.25 * np.einsum('PX,Xx,utbx->Pbtu', R1, F1_cc, R2_gg_vc, optimize=True)
    H_2body[:, :, :, :] += 0.25 * np.einsum('PX,px,tuxX->Pput', R1, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_2body[:, slice_v, :, :] += 0.25 * np.einsum('PX,Xy,tuay->Paut', R1, F1_cc, R2_gg_vc, optimize=True)
    H_2body[:, :, :, :] += 0.25 * np.einsum('PX,py,tuXy->Pptu', R1, F1_gc[:, :], R2_gg_cc, optimize=True)
    H_2body[:, slice_v, :, :] += -0.25 * np.einsum('PX,utbX,uq->Pbtq', R1, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_2body[:, slice_v, :, :] += -0.25 * np.einsum('PX,tuaX,uq->Paqt', R1, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_2body[:, slice_v, :, :] += -0.25 * np.einsum('PX,utbX,tq->Pbqu', R1, R2_gg_vc, F1_gg[:, :], optimize=True)
    H_2body[:, slice_v, :, :] += -0.25 * np.einsum('PX,tuaX,tq->Pauq', R1, R2_gg_vc, F1_gg[:, :], optimize=True)
    #  F1_R2D_R1  
    H_2body[:, :, slice_v, :] += -0.25 * np.einsum('pq,quay,Py->puaP', F1_gg[:, :], R2_gg_vc, R1, optimize=True)
    H_2body[:, :, :, slice_v] += -0.25 * np.einsum('pq,uqbx,Px->puPb', F1_gg[:, :], R2_gg_vc, R1, optimize=True)
    H_2body[:, :, slice_v, :] += -0.25 * np.einsum('pq,qtbx,Px->ptbP', F1_gg[:, :], R2_gg_vc, R1, optimize=True)
    H_2body[:, :, :, slice_v] += -0.25 * np.einsum('pq,tqay,Py->ptPa', F1_gg[:, :], R2_gg_vc, R1, optimize=True)
    H_2body[:, :, slice_v, :] += 0.25 * np.einsum('tuay,yX,PX->tuaP', R2_gg_vc, F1_cc, R1, optimize=True)
    H_2body[:, :, :, :] += 0.25 * np.einsum('tuxy,qy,Px->tuPq', R2_gg_cc, F1_gc[:, :], R1, optimize=True)
    H_2body[:, :, :, :] += 0.25 * np.einsum('tuxy,qx,Py->tuqP', R2_gg_cc, F1_gc[:, :], R1, optimize=True)
    H_2body[:, :, :, slice_v] += 0.25 * np.einsum('utbx,xX,PX->tuPb', R2_gg_vc, F1_cc, R1, optimize=True)
    #  F1_R2D_R1D  
